In [6]:
import pandas as pd

sales = pd.read_csv("../data/raw/sales_train_validation.csv")
calendar = pd.read_csv("../data/raw/calendar.csv")
prices = pd.read_csv("../data/raw/sell_prices.csv")

print("Sales Shape:", sales.shape)
print("Calendar Shape:", calendar.shape)
print("Prices Shape:", prices.shape)

Sales Shape: (30490, 1919)
Calendar Shape: (1969, 14)
Prices Shape: (6841121, 4)

In [7]:
sales.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [8]:
sales.columns[:10]

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4'],
      dtype='str')

In [9]:
sales.iloc[0]

id          HOBBIES_1_001_CA_1_validation
item_id                     HOBBIES_1_001
dept_id                         HOBBIES_1
cat_id                            HOBBIES
store_id                             CA_1
                        ...
d_1909                                  1
d_1910                                  3
d_1911                                  0
d_1912                                  1
d_1913                                  1
Name: 0, Length: 1919, dtype: object

In [10]:
sales[['item_id',
       'dept_id',
       'cat_id',
       'store_id',
       'state_id']].head()

         item_id    dept_id   cat_id store_id state_id
0  HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1       CA
1  HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1       CA
2  HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1       CA
3  HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1       CA
4  HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1       CA

In [11]:
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [12]:
calendar.columns

Index(['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd',
       'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2',
       'snap_CA', 'snap_TX', 'snap_WI'],
      dtype='str')

In [13]:
prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [14]:
prices.describe()

           wm_yr_wk    sell_price
count  6.841121e+06  6.841121e+06
mean   1.138294e+04  4.410952e+00
std    1.486100e+02  3.408814e+00
min    1.110100e+04  1.000000e-02
25%    1.124700e+04  2.180000e+00
50%    1.141100e+04  3.470000e+00
75%    1.151700e+04  5.840000e+00
max    1.162100e+04  1.073200e+02

In [15]:
prices.columns

Index(['store_id', 'item_id', 'wm_yr_wk', 'sell_price'], dtype='str')

In [16]:
sales['state_id'].nunique()
sales['store_id'].nunique()
sales['cat_id'].nunique()
sales['cat_id'].unique()
sales['dept_id'].nunique()
sales['item_id'].nunique()
len([c for c in sales.columns if c.startswith('d_')])

1913

In [17]:
print("Number of States:", sales['state_id'].nunique())

print("Number of Stores:", sales['store_id'].nunique())

print("Number of Categories:", sales['cat_id'].nunique())

print("Category Names:")
print(sales['cat_id'].unique())

print("Number of Departments:", sales['dept_id'].nunique())

print("Number of Unique Items:", sales['item_id'].nunique())

print("Number of Days:",
      len([c for c in sales.columns if c.startswith('d_')]))

Number of States: 3
Number of Stores: 10
Number of Categories: 3
Category Names:
<StringArray>
['HOBBIES', 'HOUSEHOLD', 'FOODS']
Length: 3, dtype: str
Number of Departments: 7
Number of Unique Items: 3049
Number of Days: 1913

In [18]:
id_columns = [
    'id',
    'item_id',
    'dept_id',
    'cat_id',
    'store_id',
    'state_id'
]

sales_long = pd.melt(
    sales,
    id_vars=id_columns,
    var_name='d',
    value_name='sales'
)

sales_long.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0

In [19]:
print("Long Format Shape:", sales_long.shape)

Long Format Shape: (58327370, 8)

In [20]:
print("Long Format Shape:", sales_long.shape)

Long Format Shape: (58327370, 8)

In [21]:
sales_long = sales_long.merge(
    calendar,
    on='d',
    how='left'
)

In [22]:
sales_long[['d', 'date', 'weekday', 'month', 'year']].head()

     d        date   weekday  month  year
0  d_1  2011-01-29  Saturday      1  2011
1  d_1  2011-01-29  Saturday      1  2011
2  d_1  2011-01-29  Saturday      1  2011
3  d_1  2011-01-29  Saturday      1  2011
4  d_1  2011-01-29  Saturday      1  2011

In [23]:
print(sales_long.shape)

(58327370, 21)

In [24]:
print("sales_long columns:")
print(sales_long.columns.tolist())

print("\nprices columns:")
print(prices.columns.tolist())

sales_long columns:
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd', 'sales', 'date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

prices columns:
['store_id', 'item_id', 'wm_yr_wk', 'sell_price']

In [25]:
sales_long = sales_long.merge(
    prices,
    on=['store_id', 'item_id', 'wm_yr_wk'],
    how='left'
)

In [26]:
print(sales_long.shape)
sales_long[
    ['item_id', 'store_id', 'date', 'sales', 'sell_price']
].head()

(58327370, 22)

         item_id store_id        date  sales  sell_price
0  HOBBIES_1_001     CA_1  2011-01-29      0         NaN
1  HOBBIES_1_002     CA_1  2011-01-29      0         NaN
2  HOBBIES_1_003     CA_1  2011-01-29      0         NaN
3  HOBBIES_1_004     CA_1  2011-01-29      0         NaN
4  HOBBIES_1_005     CA_1  2011-01-29      0         NaN

In [27]:
missing_pct = (
    sales_long['sell_price']
    .isna()
    .mean()
    * 100
)

print(f"Missing Price %: {missing_pct:.2f}%")

Missing Price %: 21.09%

In [28]:
sales_long['sell_price'].describe()

count    4.602796e+07
mean     4.408089e+00
std      3.403657e+00
min      1.000000e-02
25%      2.180000e+00
50%      3.470000e+00
75%      5.840000e+00
max      1.073200e+02
Name: sell_price, dtype: float64

In [29]:
sales_long['sell_price'].isna().sum()

np.int64(12299413)

In [30]:
sales_long = sales_long.sort_values(
    ['store_id', 'item_id', 'date']
)

sales_long['sell_price'] = (
    sales_long.groupby(
        ['store_id', 'item_id']
    )['sell_price']
    .ffill()
)

In [31]:
missing_pct = (
    sales_long['sell_price']
    .isna()
    .mean()
    * 100
)

print(f"Missing Price %: {missing_pct:.2f}%")

Missing Price %: 21.09%

In [32]:
sample_items = sales['item_id'].unique()[:250]

sales_subset = sales[
    sales['item_id'].isin(sample_items)
].copy()

print(sales_subset.shape)

(2500, 1919)

In [33]:
# Keep only needed columns
id_columns = [
    'id',
    'item_id',
    'dept_id',
    'cat_id',
    'store_id',
    'state_id'
]

sales_long = pd.melt(
    sales_subset,
    id_vars=id_columns,
    var_name='d',
    value_name='sales'
)

print(sales_long.shape)

(4782500, 8)

In [34]:
sales_long = sales_long.merge(
    calendar,
    on='d',
    how='left'
)

print(sales_long.shape)

(4782500, 21)

In [35]:
sales_long[
    ['d', 'date', 'weekday', 'month', 'year']
].head()

     d        date   weekday  month  year
0  d_1  2011-01-29  Saturday      1  2011
1  d_1  2011-01-29  Saturday      1  2011
2  d_1  2011-01-29  Saturday      1  2011
3  d_1  2011-01-29  Saturday      1  2011
4  d_1  2011-01-29  Saturday      1  2011

In [36]:
sales_long = sales_long.merge(
    prices,
    on=['store_id', 'item_id', 'wm_yr_wk'],
    how='left'
)

print(sales_long.shape)

(4782500, 22)

In [37]:
missing_pct = (
    sales_long['sell_price']
    .isna()
    .mean()
    * 100
)

print(f"Missing Price %: {missing_pct:.2f}%")

Missing Price %: 19.85%

In [38]:
sales_long['date'] = pd.to_datetime(sales_long['date'])

print(sales_long['date'].dtype)

datetime64[us]

In [39]:
sales_long = sales_long.sort_values(
    ['store_id', 'item_id', 'date']
)

sales_long.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
2500,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,...,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
5000,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,...,1,2011,NaN,NaN,NaN,NaN,0,0,0,NaN
7500,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,...,2,2011,NaN,NaN,NaN,NaN,1,1,0,NaN
10000,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,...,2,2011,NaN,NaN,NaN,NaN,1,0,1,NaN

In [40]:
sales_long['lag_7'] = (
    sales_long
    .groupby(['store_id', 'item_id'])['sales']
    .shift(7)
)

In [41]:
sales_long[
    ['date', 'sales', 'lag_7']
].head(15)

            date  sales  lag_7
0     2011-01-29      0    NaN
2500  2011-01-30      0    NaN
5000  2011-01-31      0    NaN
7500  2011-02-01      0    NaN
10000 2011-02-02      0    NaN
12500 2011-02-03      0    NaN
15000 2011-02-04      0    NaN
17500 2011-02-05      0    0.0
20000 2011-02-06      0    0.0
22500 2011-02-07      0    0.0
25000 2011-02-08      0    0.0
27500 2011-02-09      0    0.0
30000 2011-02-10      0    0.0
32500 2011-02-11      0    0.0
35000 2011-02-12      0    0.0

In [42]:
sales_long['date'] = pd.to_datetime(sales_long['date'])

sales_long = sales_long.sort_values(
    ['store_id', 'item_id', 'date']
)

sales_long['lag_7'] = (
    sales_long
    .groupby(['store_id', 'item_id'])['sales']
    .shift(7)
)

sales_long[
    ['date', 'sales', 'lag_7']
].head(15)

            date  sales  lag_7
0     2011-01-29      0    NaN
2500  2011-01-30      0    NaN
5000  2011-01-31      0    NaN
7500  2011-02-01      0    NaN
10000 2011-02-02      0    NaN
12500 2011-02-03      0    NaN
15000 2011-02-04      0    NaN
17500 2011-02-05      0    0.0
20000 2011-02-06      0    0.0
22500 2011-02-07      0    0.0
25000 2011-02-08      0    0.0
27500 2011-02-09      0    0.0
30000 2011-02-10      0    0.0
32500 2011-02-11      0    0.0
35000 2011-02-12      0    0.0

In [43]:
sales_long['lag_14'] = (
    sales_long
    .groupby(['store_id', 'item_id'])['sales']
    .shift(14)
)

sales_long['lag_28'] = (
    sales_long
    .groupby(['store_id', 'item_id'])['sales']
    .shift(28)
)

In [44]:
sample = sales_long[
    sales_long['item_id'] == sales_long['item_id'].iloc[0]
][['date', 'sales', 'lag_7', 'lag_14', 'lag_28']]

sample.head(35)

            date  sales  lag_7  lag_14  lag_28
0     2011-01-29      0    NaN     NaN     NaN
2500  2011-01-30      0    NaN     NaN     NaN
5000  2011-01-31      0    NaN     NaN     NaN
7500  2011-02-01      0    NaN     NaN     NaN
10000 2011-02-02      0    NaN     NaN     NaN
12500 2011-02-03      0    NaN     NaN     NaN
15000 2011-02-04      0    NaN     NaN     NaN
17500 2011-02-05      0    0.0     NaN     NaN
20000 2011-02-06      0    0.0     NaN     NaN
22500 2011-02-07      0    0.0     NaN     NaN
25000 2011-02-08      0    0.0     NaN     NaN
27500 2011-02-09      0    0.0     NaN     NaN
30000 2011-02-10      0    0.0     NaN     NaN
32500 2011-02-11      0    0.0     NaN     NaN
35000 2011-02-12      0    0.0     0.0     NaN
37500 2011-02-13      0    0.0     0.0     NaN
40000 2011-02-14      0    0.0     0.0     NaN
42500 2011-02-15      0    0.0     0.0     NaN
45000 2011-02-16      0    0.0     0.0     NaN
47500 2011-02-17      0    0.0     0.0     NaN
50000 2011-02-18      0    0.0     0.0     NaN
52500 2011-02-19      0    0.0     0.0     NaN
55000 2011-02-20      0    0.0     0.0     NaN
57500 2011-02-21      0    0.0     0.0     NaN
60000 2011-02-22      0    0.0     0.0     NaN
62500 2011-02-23      0    0.0     0.0     NaN
65000 2011-02-24      0    0.0     0.0     NaN
67500 2011-02-25      0    0.0     0.0     NaN
70000 2011-02-26      0    0.0     0.0     0.0
72500 2011-02-27      0    0.0     0.0     0.0
75000 2011-02-28      0    0.0     0.0     0.0
77500 2011-03-01      0    0.0     0.0     0.0
80000 2011-03-02      0    0.0     0.0     0.0
82500 2011-03-03      0    0.0     0.0     0.0
85000 2011-03-04      0    0.0     0.0     0.0

In [45]:
sales_long['rolling_mean_7'] = (
    sales_long
    .groupby(['store_id', 'item_id'])['sales']
    .transform(
        lambda x: x.shift(1).rolling(7).mean()
    )
)

sales_long['rolling_mean_28'] = (
    sales_long
    .groupby(['store_id', 'item_id'])['sales']
    .transform(
        lambda x: x.shift(1).rolling(28).mean()
    )
)

In [46]:
sample = sales_long[
    sales_long['item_id'] == sales_long['item_id'].iloc[0]
][[
    'date',
    'sales',
    'rolling_mean_7',
    'rolling_mean_28'
]]

sample.head(40)

            date  sales  rolling_mean_7  rolling_mean_28
0     2011-01-29      0             NaN              NaN
2500  2011-01-30      0             NaN              NaN
5000  2011-01-31      0             NaN              NaN
7500  2011-02-01      0             NaN              NaN
10000 2011-02-02      0             NaN              NaN
12500 2011-02-03      0             NaN              NaN
15000 2011-02-04      0             NaN              NaN
17500 2011-02-05      0             0.0              NaN
20000 2011-02-06      0             0.0              NaN
22500 2011-02-07      0             0.0              NaN
25000 2011-02-08      0             0.0              NaN
27500 2011-02-09      0             0.0              NaN
30000 2011-02-10      0             0.0              NaN
32500 2011-02-11      0             0.0              NaN
35000 2011-02-12      0             0.0              NaN
37500 2011-02-13      0             0.0              NaN
40000 2011-02-14      0             0.0              NaN
42500 2011-02-15      0             0.0              NaN
45000 2011-02-16      0             0.0              NaN
47500 2011-02-17      0             0.0              NaN
50000 2011-02-18      0             0.0              NaN
52500 2011-02-19      0             0.0              NaN
55000 2011-02-20      0             0.0              NaN
57500 2011-02-21      0             0.0              NaN
60000 2011-02-22      0             0.0              NaN
62500 2011-02-23      0             0.0              NaN
65000 2011-02-24      0             0.0              NaN
67500 2011-02-25      0             0.0              NaN
70000 2011-02-26      0             0.0              0.0
72500 2011-02-27      0             0.0              0.0
75000 2011-02-28      0             0.0              0.0
77500 2011-03-01      0             0.0              0.0
80000 2011-03-02      0             0.0              0.0
82500 2011-03-03      0             0.0              0.0
85000 2011-03-04      0             0.0              0.0
87500 2011-03-05      0             0.0              0.0
90000 2011-03-06      0             0.0              0.0
92500 2011-03-07      0             0.0              0.0
95000 2011-03-08      0             0.0              0.0
97500 2011-03-09      0             0.0              0.0

In [47]:
sales_long['price_lag_7'] = (
    sales_long
    .groupby(['store_id', 'item_id'])['sell_price']
    .shift(7)
)

In [48]:
sales_long['price_change_pct'] = (
    (sales_long['sell_price'] - sales_long['price_lag_7'])
    / sales_long['price_lag_7']
)

In [49]:
sales_long['discount_flag'] = (
    sales_long['price_change_pct'] < 0
).astype(int)

In [50]:
sales_long[
    [
        'date',
        'sell_price',
        'price_lag_7',
        'price_change_pct',
        'discount_flag'
    ]
].head(50)

             date  sell_price  price_lag_7  price_change_pct  discount_flag
0      2011-01-29         NaN          NaN               NaN              0
2500   2011-01-30         NaN          NaN               NaN              0
5000   2011-01-31         NaN          NaN               NaN              0
7500   2011-02-01         NaN          NaN               NaN              0
10000  2011-02-02         NaN          NaN               NaN              0
12500  2011-02-03         NaN          NaN               NaN              0
15000  2011-02-04         NaN          NaN               NaN              0
17500  2011-02-05         NaN          NaN               NaN              0
20000  2011-02-06         NaN          NaN               NaN              0
22500  2011-02-07         NaN          NaN               NaN              0
25000  2011-02-08         NaN          NaN               NaN              0
27500  2011-02-09         NaN          NaN               NaN              0
30000  2011-02-10         NaN          NaN               NaN              0
32500  2011-02-11         NaN          NaN               NaN              0
35000  2011-02-12         NaN          NaN               NaN              0
37500  2011-02-13         NaN          NaN               NaN              0
40000  2011-02-14         NaN          NaN               NaN              0
42500  2011-02-15         NaN          NaN               NaN              0
45000  2011-02-16         NaN          NaN               NaN              0
47500  2011-02-17         NaN          NaN               NaN              0
50000  2011-02-18         NaN          NaN               NaN              0
52500  2011-02-19         NaN          NaN               NaN              0
55000  2011-02-20         NaN          NaN               NaN              0
57500  2011-02-21         NaN          NaN               NaN              0
60000  2011-02-22         NaN          NaN               NaN              0
62500  2011-02-23         NaN          NaN               NaN              0
65000  2011-02-24         NaN          NaN               NaN              0
67500  2011-02-25         NaN          NaN               NaN              0
70000  2011-02-26         NaN          NaN               NaN              0
72500  2011-02-27         NaN          NaN               NaN              0
75000  2011-02-28         NaN          NaN               NaN              0
77500  2011-03-01         NaN          NaN               NaN              0
80000  2011-03-02         NaN          NaN               NaN              0
82500  2011-03-03         NaN          NaN               NaN              0
85000  2011-03-04         NaN          NaN               NaN              0
87500  2011-03-05         NaN          NaN               NaN              0
90000  2011-03-06         NaN          NaN               NaN              0
92500  2011-03-07         NaN          NaN               NaN              0
95000  2011-03-08         NaN          NaN               NaN              0
97500  2011-03-09         NaN          NaN               NaN              0
100000 2011-03-10         NaN          NaN               NaN              0
102500 2011-03-11         NaN          NaN               NaN              0
105000 2011-03-12         NaN          NaN               NaN              0
107500 2011-03-13         NaN          NaN               NaN              0
110000 2011-03-14         NaN          NaN               NaN              0
112500 2011-03-15         NaN          NaN               NaN              0
115000 2011-03-16         NaN          NaN               NaN              0
117500 2011-03-17         NaN          NaN               NaN              0
120000 2011-03-18         NaN          NaN               NaN              0
122500 2011-03-19         NaN          NaN               NaN              0

In [51]:
sales_long['sell_price'].notna().sum()

np.int64(3833027)

In [52]:
sales_long['sell_price'].isna().sum()

np.int64(949473)

In [53]:
sales_long[
    sales_long['sell_price'].notna()
][[
    'item_id',
    'store_id',
    'date',
    'sell_price'
]].head(20)

               item_id store_id       date  sell_price
2240000  HOBBIES_1_001     CA_1 2013-07-13        9.58
2242500  HOBBIES_1_001     CA_1 2013-07-14        9.58
2245000  HOBBIES_1_001     CA_1 2013-07-15        9.58
2247500  HOBBIES_1_001     CA_1 2013-07-16        9.58
2250000  HOBBIES_1_001     CA_1 2013-07-17        9.58
2252500  HOBBIES_1_001     CA_1 2013-07-18        9.58
2255000  HOBBIES_1_001     CA_1 2013-07-19        9.58
2257500  HOBBIES_1_001     CA_1 2013-07-20        9.58
2260000  HOBBIES_1_001     CA_1 2013-07-21        9.58
2262500  HOBBIES_1_001     CA_1 2013-07-22        9.58
2265000  HOBBIES_1_001     CA_1 2013-07-23        9.58
2267500  HOBBIES_1_001     CA_1 2013-07-24        9.58
2270000  HOBBIES_1_001     CA_1 2013-07-25        9.58
2272500  HOBBIES_1_001     CA_1 2013-07-26        9.58
2275000  HOBBIES_1_001     CA_1 2013-07-27        8.26
2277500  HOBBIES_1_001     CA_1 2013-07-28        8.26
2280000  HOBBIES_1_001     CA_1 2013-07-29        8.26
2282500  HOBBIES_1_001     CA_1 2013-07-30        8.26
2285000  HOBBIES_1_001     CA_1 2013-07-31        8.26
2287500  HOBBIES_1_001     CA_1 2013-08-01        8.26

In [54]:
sales_long[
    sales_long['sell_price'].notna()
][[
    'date',
    'sell_price',
    'price_lag_7',
    'price_change_pct',
    'discount_flag'
]].head(30)

              date  sell_price  price_lag_7  price_change_pct  discount_flag
2240000 2013-07-13        9.58          NaN               NaN              0
2242500 2013-07-14        9.58          NaN               NaN              0
2245000 2013-07-15        9.58          NaN               NaN              0
2247500 2013-07-16        9.58          NaN               NaN              0
2250000 2013-07-17        9.58          NaN               NaN              0
2252500 2013-07-18        9.58          NaN               NaN              0
2255000 2013-07-19        9.58          NaN               NaN              0
2257500 2013-07-20        9.58         9.58          0.000000              0
2260000 2013-07-21        9.58         9.58          0.000000              0
2262500 2013-07-22        9.58         9.58          0.000000              0
2265000 2013-07-23        9.58         9.58          0.000000              0
2267500 2013-07-24        9.58         9.58          0.000000              0
2270000 2013-07-25        9.58         9.58          0.000000              0
2272500 2013-07-26        9.58         9.58          0.000000              0
2275000 2013-07-27        8.26         9.58         -0.137787              1
2277500 2013-07-28        8.26         9.58         -0.137787              1
2280000 2013-07-29        8.26         9.58         -0.137787              1
2282500 2013-07-30        8.26         9.58         -0.137787              1
2285000 2013-07-31        8.26         9.58         -0.137787              1
2287500 2013-08-01        8.26         9.58         -0.137787              1
2290000 2013-08-02        8.26         9.58         -0.137787              1
2292500 2013-08-03        8.26         8.26          0.000000              0
2295000 2013-08-04        8.26         8.26          0.000000              0
2297500 2013-08-05        8.26         8.26          0.000000              0
2300000 2013-08-06        8.26         8.26          0.000000              0
2302500 2013-08-07        8.26         8.26          0.000000              0
2305000 2013-08-08        8.26         8.26          0.000000              0
2307500 2013-08-09        8.26         8.26          0.000000              0
2310000 2013-08-10        8.26         8.26          0.000000              0
2312500 2013-08-11        8.26         8.26          0.000000              0

In [55]:
sales_long['is_weekend'] = (
    sales_long['weekday']
    .isin(['Saturday', 'Sunday'])
).astype(int)

sales_long['has_event'] = (
    sales_long['event_name_1']
    .notna()
).astype(int)

sales_long['week_of_year'] = (
    sales_long['date']
    .dt.isocalendar()
    .week
    .astype(int)
)

In [56]:
sales_long[[
    'date',
    'weekday',
    'is_weekend',
    'event_name_1',
    'has_event',
    'week_of_year'
]].head(20)

,date,weekday,is_weekend,event_name_1,has_event,week_of_year
0,2011-01-29,Saturday,1,NaN,0,4
2500,2011-01-30,Sunday,1,NaN,0,4
5000,2011-01-31,Monday,0,NaN,0,5
7500,2011-02-01,Tuesday,0,NaN,0,5
10000,2011-02-02,Wednesday,0,NaN,0,5
12500,2011-02-03,Thursday,0,NaN,0,5
15000,2011-02-04,Friday,0,NaN,0,5
17500,2011-02-05,Saturday,1,NaN,0,5
20000,2011-02-06,Sunday,1,SuperBowl,1,5
22500,2011-02-07,Monday,0,NaN,0,6
25000,2011-02-08,Tuesday,0,NaN,0,6
27500,2011-02-09,Wednesday,0,NaN,0,6
30000,2011-02-10,Thursday,0,NaN,0,6
32500,2011-02-11,Friday,0,NaN,0,6
35000,2011-02-12,Saturday,1,NaN,0,6
37500,2011-02-13,Sunday,1,NaN,0,6
40000,2011-02-14,Monday,0,ValentinesDay,1,7
42500,2011-02-15,Tuesday,0,NaN,0,7
45000,2011-02-16,Wednesday,0,NaN,0,7
47500,2011-02-17,Thursday,0,NaN,0,7

In [57]:
sales_long['date'].min(), sales_long['date'].max()

(Timestamp('2011-01-29 00:00:00'), Timestamp('2016-04-24 00:00:00'))

In [58]:
import pandas as pd
cutoff_date = pd.Timestamp('2014-01-01')

model_df = sales_long[
    sales_long['date'] >= cutoff_date
].copy()

print(model_df.shape)

print("Start:", model_df['date'].min())
print("End:", model_df['date'].max())

(2112500, 33)
Start: 2014-01-01 00:00:00
End: 2016-04-24 00:00:00

validation_start = (
    model_df['date'].max() -
    pd.Timedelta(days=27)
)

train_df = model_df[
    model_df['date'] < validation_start
].copy()

valid_df = model_df[
    model_df['date'] >= validation_start
].copy()

print("Train Shape :", train_df.shape)
print("Valid Shape :", valid_df.shape)

print("\nTrain Date Range")
print(train_df['date'].min(), "to", train_df['date'].max())

print("\nValidation Date Range")
print(valid_df['date'].min(), "to", valid_df['date'].max())

In [59]:
validation_start = (
    model_df['date'].max() -
    pd.Timedelta(days=27)
)

train_df = model_df[
    model_df['date'] < validation_start
].copy()

valid_df = model_df[
    model_df['date'] >= validation_start
].copy()

print("Train Shape :", train_df.shape)
print("Valid Shape :", valid_df.shape)

print("\nTrain Date Range")
print(train_df['date'].min(), "to", train_df['date'].max())

print("\nValidation Date Range")
print(valid_df['date'].min(), "to", valid_df['date'].max())

Train Shape : (2042500, 33)
Valid Shape : (70000, 33)

Train Date Range
2014-01-01 00:00:00 to 2016-03-27 00:00:00

Validation Date Range
2016-03-28 00:00:00 to 2016-04-24 00:00:00

In [60]:
feature_cols = [
    # Demand history
    'lag_7',
    'lag_14',
    'lag_28',
    'rolling_mean_7',
    'rolling_mean_28',

    # Price features
    'sell_price',
    'price_change_pct',
    'discount_flag',

    # Calendar features
    'month',
    'year',
    'week_of_year',
    'is_weekend',

    # SNAP
    'snap_CA',
    'snap_TX',
    'snap_WI',

    # Events
    'has_event'
]

target_col = 'sales'

print("Number of Features:", len(feature_cols))
print(feature_cols)

Number of Features: 16
['lag_7', 'lag_14', 'lag_28', 'rolling_mean_7', 'rolling_mean_28', 'sell_price', 'price_change_pct', 'discount_flag', 'month', 'year', 'week_of_year', 'is_weekend', 'snap_CA', 'snap_TX', 'snap_WI', 'has_event']

In [61]:
train_model = train_df.dropna(subset=feature_cols + [target_col])

valid_model = valid_df.dropna(subset=feature_cols + [target_col])

print("Train Shape:", train_model.shape)
print("Valid Shape:", valid_model.shape)

Train Shape: (1999737, 33)
Valid Shape: (70000, 33)

In [62]:
X_train = train_model[feature_cols]
y_train = train_model[target_col]

X_valid = valid_model[feature_cols]
y_valid = valid_model[target_col]

print(X_train.shape)
print(X_valid.shape)

(1999737, 16)
(70000, 16)

In [63]:
pip install lightgbm

Requirement already satisfied: lightgbm in d:\retailiq\venv\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in d:\retailiq\venv\lib\site-packages (from lightgbm) (2.4.6)
Requirement already satisfied: scipy in d:\retailiq\venv\lib\site-packages (from lightgbm) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
from lightgbm import LGBMRegressor

lgb_model = LGBMRegressor(
    n_estimators=200,
    learning_rate=0.05,
    num_leaves=31,
    random_state=42,
    n_jobs=-1
)

lgb_model.fit(
    X_train,
    y_train
)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.147664 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1057
[LightGBM] [Info] Number of data points in the train set: 1999737, number of used features: 16
[LightGBM] [Info] Start training from score 0.768896

LGBMRegressor(learning_rate=0.05, n_estimators=200, n_jobs=-1, random_state=42)

In [65]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\retailiq\venv\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in d:\retailiq\venv\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in d:\retailiq\venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in d:\retailiq\venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in d:\retailiq\venv\lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in d:\retailiq\venv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [66]:
valid_preds = lgb_model.predict(X_valid)

print(valid_preds[:10])

[0.8460134  0.9160101  0.85533545 0.81859842 0.85858787 0.96936296
 1.03087361 0.76066221 0.77241628 0.89692347]

In [67]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_valid,
        valid_preds
    )
)

print("RMSE:", rmse)

RMSE: 1.8562752538601754

In [68]:
model_df

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,lag_14,lag_28,rolling_mean_7,rolling_mean_28,price_lag_7,price_change_pct,discount_flag,is_weekend,has_event,week_of_year
2670000,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1069,1,2014-01-01,11349,...,1.0,1.0,0.000000,0.642857,8.26,0.0,0,0,1,1
2672500,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1070,1,2014-01-02,11349,...,2.0,0.0,0.142857,0.642857,8.26,0.0,0,0,0,1
2675000,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1071,0,2014-01-03,11349,...,0.0,1.0,0.285714,0.678571,8.26,0.0,0,0,0,1
2677500,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1072,0,2014-01-04,11350,...,1.0,1.0,0.285714,0.642857,8.26,0.0,0,1,0,1
2680000,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1073,0,2014-01-05,11350,...,1.0,0.0,0.285714,0.607143,8.26,0.0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4772499,HOBBIES_1_257_WI_3_validation,HOBBIES_1_257,HOBBIES_1,HOBBIES,WI_3,WI,d_1909,0,2016-04-20,11612,...,0.0,0.0,0.000000,0.000000,16.76,0.0,0,0,0,16
4774999,HOBBIES_1_257_WI_3_validation,HOBBIES_1_257,HOBBIES_1,HOBBIES,WI_3,WI,d_1910,1,2016-04-21,11612,...,0.0,0.0,0.000000,0.000000,16.76,0.0,0,0,0,16
4777499,HOBBIES_1_257_WI_3_validation,HOBBIES_1_257,HOBBIES_1,HOBBIES,WI_3,WI,d_1911,0,2016-04-22,11612,...,0.0,0.0,0.142857,0.035714,16.76,0.0,0,0,0,16
4779999,HOBBIES_1_257_WI_3_validation,HOBBIES_1_257,HOBBIES_1,HOBBIES,WI_3,WI,d_1912,0,2016-04-23,11613,...,0.0,0.0,0.142857,0.035714,16.76,0.0,0,1,0,16
4782499,HOBBIES_1_257_WI_3_validation,HOBBIES_1_257,HOBBIES_1,HOBBIES,WI_3,WI,d_1913,0,2016-04-24,11613,...,0.0,0.0,0.142857,0.035714,16.76,0.0,0,1,0,16

In [71]:
model_df.to_parquet(
    "../data/processed/model_dataset.parquet",
    index=False
)

ArrowKeyError: No type extension with name arrow.py_extension_type found

In [70]:
pip install pyarrow

Collecting pyarrow
  Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl.metadata (3.0 kB)
Downloading pyarrow-24.0.0-cp313-cp313-win_amd64.whl (27.3 MB)
   ---------------------------------------- 0.0/27.3 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.3 MB 4.1 MB/s eta 0:00:07
   -- ------------------------------------- 1.6/27.3 MB 4.1 MB/s eta 0:00:07
   --- ------------------------------------ 2.6/27.3 MB 4.3 MB/s eta 0:00:06
   ---- ----------------------------------- 3.4/27.3 MB 4.2 MB/s eta 0:00:06
   ------ --------------------------------- 4.2/27.3 MB 4.2 MB/s eta 0:00:06
   ------- -------------------------------- 5.0/27.3 MB 4.2 MB/s eta 0:00:06
   -------- ------------------------------- 6.0/27.3 MB 4.2 MB/s eta 0:00:06
   ---------- ----------------------------- 7.1/27.3 MB 4.3 MB/s eta 0:00:05
   ----------- ---------------------------- 7.9/27.3 MB 4.3 MB/s eta 0:00:05
   ------------- -------------------------- 8.9/27.3 MB 4.3 MB/s eta 0:00:05
   -------------- ------------------------- 9.7/27.3 MB 4.3 MB/s eta 0:00:05
   --------------- ------------------------ 10.5/27.3 MB 4.2 MB/s eta 0:00:04
   ---------------- ----------------------- 11.3/27.3 MB 4.3 MB/s eta 0:00:04
   ------------------ --------------------- 12.3/27.3 MB 4.3 MB/s eta 0:00:04
   ------------------- -------------------- 13.4/27.3 MB 4.3 MB/s eta 0:00:04
   -------------------- ------------------- 14.2/27.3 MB 4.3 MB/s eta 0:00:04
   --------------------- ------------------ 14.9/27.3 MB 4.3 MB/s eta 0:00:03
   ----------------------- ---------------- 15.7/27.3 MB 4.3 MB/s eta 0:00:03
   ------------------------ --------------- 16.8/27.3 MB 4.3 MB/s eta 0:00:03
   -------------------------- ------------- 18.1/27.3 MB 4.4 MB/s eta 0:00:03
   ---------------------------- ----------- 19.4/27.3 MB 4.5 MB/s eta 0:00:02
   ------------------------------ --------- 20.7/27.3 MB 4.6 MB/s eta 0:00:02
   -------------------------------- ------- 22.0/27.3 MB 4.6 MB/s eta 0:00:02
   --------------------------------- ------ 23.1/27.3 MB 4.7 MB/s eta 0:00:01
   ---------------------------------- ----- 23.9/27.3 MB 4.7 MB/s eta 0:00:01
   ------------------------------------ --- 24.6/27.3 MB 4.6 MB/s eta 0:00:01
   ------------------------------------- -- 25.4/27.3 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 26.0/27.3 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 26.5/27.3 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.3 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 27.3/27.3 MB 4.3 MB/s  0:00:06
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [72]:
model_df.to_parquet(
    "../data/processed/model_dataset.parquet",
    index=False
)

ArrowKeyError: A type extension with name pandas.period already defined

In [73]:
import pyarrow

print(pyarrow.__version__)

24.0.0

In [74]:
import pandas as pd

print(pd.__version__)

3.0.3

In [75]:
import pandas as pd

test_df = pd.DataFrame({
    "a": [1, 2, 3]
})

test_df.to_parquet(
    "../data/processed/test.parquet",
    index=False
)

print("Success")

ArrowKeyError: A type extension with name pandas.period already defined